### PR TITLE
improved requests code and changed packages' name

### PR DESCRIPTION
**Pull request by ALiwoto**
Signed-off-by: Aliwoto <aminnimaj@gmail.com>

### CODE REVIEW

**Review by Dank-del — COMMENTED** [review]
Why even change folder names?

**Comment by ALiwoto** [comment]
They should start with lower letters

**Comment by ALiwoto** [comment]
Both package names and directory names

**Comment by ALiwoto** [comment]
Tho don't know if there is a real reason for it or not, but it's one of the rules in go code styles

**Comment by ALiwoto** [comment]
image
see, everything in their own official packages are started with lower case

**Comment by ALiwoto** [comment]
Also module names should be started with a supported Google's ÜberProxy host url (like github.com or golang.org)
Go compiler supports these urls, so the only thing users have to do to use the library is to write `go get -u <url>`

**Comment by ALiwoto** [comment]
AAAAAAAAA I think I've done something wrong in module name

**Comment by ALiwoto** [comment]
the url here is `https://github.com/Dank-del/anilistWrapGO` but in go.mod I entered `module github.com/Dank-del/anilistWrapGo`
I will fix it

**Comment by Dank-del** [comment]
> Tho don't know if there is a real reason for it or not, but it's one of the rules in go code styles

There doesn't seem to be any particular difference other than looks and breaking the file history on git

**Comment by Dank-del** [comment]
> the url here is `https://github.com/Dank-del/anilistWrapGO` but in go.mod I entered `module github.com/Dank-del/anilistWrapGo`
> I will fix it

Cases in URLs don't make any difference most of the time.

**Comment by ALiwoto** [comment]
> > the url here is `https://github.com/Dank-del/anilistWrapGO` but in go.mod I entered `module github.com/Dank-del/anilistWrapGo`
> > I will fix it
> 
> Cases in URLs don't make any difference most of the time.

it makes in `pkg.go.dev/`
it's case sensitive

**Comment by itspranavajay** [comment]
> > > the url here is `https://github.com/Dank-del/anilistWrapGO` but in go.mod I entered `module github.com/Dank-del/anilistWrapGo`
> > > I will fix it
> > 
> > 
> > Cases in URLs don't make any difference most of the time.
> 
> it makes in `pkg.go.dev/`
> it's case sensitive

🤔🤔🤔

**Comment by ALiwoto** [comment]
If you are wondering why we should use `module github.com/Dank-del/anilistWrapGO` instead of `anilistWrapGO`

image

**Comment by ALiwoto** [comment]
> > Tho don't know if there is a real reason for it or not, but it's one of the rules in go code styles
> 
> There doesn't seem to be any particular difference other than looks and breaking the file history on git

Can't help that
I think we have to follow a country's rules when we are doing our stuff in it, right?
You can look at their std library, all of them are starting with lower cases like `testing`, `log`, `net/http`

**Comment by ALiwoto** [comment]
> > the url here is `https://github.com/Dank-del/anilistWrapGO` but in go.mod I entered `module github.com/Dank-del/anilistWrapGo`
> > I will fix it
> 
> Cases in URLs don't make any difference most of the time.

compare these two:

image

image

they are exactly the same, but only `G` is there instead of `g`

**Comment by ALiwoto** [comment]
Okay, I don't know what happened here, since I didn't use goland for it
fix it please if it causes any problems on your side
image

**Comment by ALiwoto** [comment]
> > > > the url here is `https://github.com/Dank-del/anilistWrapGO` but in go.mod I entered `module github.com/Dank-del/anilistWrapGo`
> > > > I will fix it
> > > 
> > > 
> > > Cases in URLs don't make any difference most of the time.
> > 
> > 
> > it makes in `pkg.go.dev/`
> > it's case sensitive
> 
> thinkingthinkingthinking

btw, you are an assembly enjoyer?

**Comment by ALiwoto** [comment]
@Dank-del by the way, you didn't tell me which part should I help you in `chizuru-go`?
(and don't ignore this please)
(also don't forget invite)

**Comment by Dank-del** [comment]
> > > the url here is `https://github.com/Dank-del/anilistWrapGO` but in go.mod I entered `module github.com/Dank-del/anilistWrapGo`
> > > I will fix it
> > 
> > 
> > Cases in URLs don't make any difference most of the time.
> 
> compare these two:
> 
> image
> 
> image
> 
> they are exactly the same, but only `G` is there instead of `g`

Dumb design

**Comment by ALiwoto** [comment]
> > > > the url here is `https://github.com/Dank-del/anilistWrapGO` but in go.mod I entered `module github.com/Dank-del/anilistWrapGo`
> > > > I will fix it
> > > 
> > > 
> > > Cases in URLs don't make any difference most of the time.
> > 
> > 
> > compare these two:
> > image
> > image
> > they are exactly the same, but only `G` is there instead of `g`
> 
> Dumb design

It wasn't like before, was it?
they changed it recently ig

**Comment by Dank-del** [comment]
> @Dank-del by the way, you didn't tell me which part should I help you in `chizuru-go`?
> (and don't ignore this please)
> (also don't forget invite)

Nvm, I got the important part done for now, try running it if you wanna.

**Comment by ALiwoto** [comment]
> > @Dank-del by the way, you didn't tell me which part should I help you in `chizuru-go`?
> > (and don't ignore this please)
> > (also don't forget invite)
> 
> Nvm, I got the important part done for now, try running it if you wanna.

Noooo, I do mind
I want to help as well

**Comment by ALiwoto** [comment]
> > @Dank-del by the way, you didn't tell me which part should I help you in `chizuru-go`?
> > (and don't ignore this please)
> > (also don't forget invite)
> 
> Nvm, I got the important part done for now, try running it if you wanna.

Okay okay, I won't copy any code from anywhere, will promise
so let me help as well .-.

**Pull request merged**
